### ISSUE TITLE
Link Spring Security to DB and Admin Roles

### ISSUE THREAD

**Issue by nakulnandhakumar** [aryan114/Tri3Drone#1]
- [x] Configure Spring Security and Map to Login
- [x] Create Custom UserName Password
- [x] Set up Permission-Based Roles (NEW)
- [x] Link Username/Password Code to DB (NEW)

[Update Users for Authentication](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Security/ApplicationSecurityConfig.java#L53-L66)
[Data Transfer Object for UserInfo](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/mysql/models/User.java#L16-L36)

**Comment by PranavKambhampati** [comment]
Hey Nakul, I think setting up Spring Security is a great way to secure our project, however, I feel like we need to further discuss the role of security in our project. I think we need to come up with where we need to use Spring Security to protect something specific in our project - maybe sensitive stuff like the analytics page or the form creator? However, I think your goals for next week are really strong!

**Comment by aryan114** [comment]
Hey Nakul, I think the progress in Spring Security is very good, I think this is an integral part of our project as it will streamline the roles between admin and a user.

**Comment by mhayescs19** [comment]
I agree with @PranavKambhampati on the concept of tiered roles, I believe since this project may be accessed in the future, not all pages will need to be "protected" behind a user account.

**Comment by mhayescs19** [comment]
The effort to complete DB integration with Spring Security was successful due to the collaborative effort. Since we both focused on two different pieces, we were effective in sharing ideas to integrate the two systems together.

**Comment by PranavKambhampati** [comment]
Hey Nakul, it's pretty cool that you were pretty much able to finish the Spring Security aspect of our project. I believe that we're on the right track to finishing our project. The next step would just be retrieving the users' responses from the database and creating the analytics charts.

**Comment by aryan114** [comment]
Hey Nakul, it's really nice to see that you were able to finish Spring Security. I believe this will be an integral part of our project. Like Pranav said, I think the next aspect to finishing our project would be Admin and Student roles and actually taking the quiz/form.
