### ISSUE TITLE
Login/Logout Page

### ISSUE THREAD

**Issue by nakulnandhakumar** [aryan114/Tri3Drone#5]
**SCORE: 3/3**

- [x] Create HTML Login/Logout Page
- [x] Style Using CSS
- [x] Link to Spring Security

_**Username:** annasmith
**Password:** password_ 

**Tangibles:** 
[LOGIN](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/login)
[LOGOUT](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/logout)

**Code:** 
[Security Username/Password Config](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Security/ApplicationSecurityConfig.java#L27-L28)
[Password Encryption](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Security/PasswordConfig.java#L12)
[Login Page](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/security/login.html)
[Logout Page](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/security/logout.html)

_Reviewd by Michael Hayes_

**Comment by mhayescs19** [comment]
Login is successful on EC2 instance, verified by @mhayescs19

**Comment by jm1021** [comment]
Nice to see well described ticket and meeting all the objectives.  As I look at the code I see you found some built in library with a bunch of .notation attributes.  Is this building  database as well, as I did not notice a POJO.  When I look at form and page I do think you can probably get content from Bootstrap without requirement of maintaining CSS.  One thing that I would like you to think about is have a Username and Password in Menu bar.   We want to make sure that only a few things are blocked by password, most of the site should be viewable by a guest.  5/3
