### ISSUE TITLE
Create connection between Admin Form and Database

### ISSUE THREAD

**Issue by aryan114** [aryan114/Tri3Drone#67]
- [x] Research and find viable solution for a dynamic form (CSS and JavaScript)
- [x] Create new controller for MC
- [x] Collaborate with @mhayescs19 on database implementation
- [x] Implement Form UI aspects into database, number of questions, number of responses for each question added

**Goal**
My goal this week was to begin the database implementation for the form UI. I was able to achieve this with the help of Michael @mhayescs19 . We worked on Tuesday evening to add certain aspects of the form UI to the database and SQL models. We were able to create the form objects, and add the list of questions into the form object through an arraylist. However, we still need to save the form, as we encountered a white label when trying to save the form. I was also able to find a solution using CSS and JavaScript to hide/show elements to make the form more dynamic, will be implemented once database implementation finished.

**Links**
[SQL](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/java/com/example/demo/MCController.java#L19)
[Controller Link](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/java/com/example/demo/MCController.java#L1)
[Database Object Creation Lines 79-84](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/java/com/example/demo/MCController.java#L79)
[Creating Form Question Object](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/java/com/example/demo/MCController.java#L91)
[Adding Questions and Answers to Form Question Object](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/java/com/example/demo/MCController.java#L93)
[CSS Hiding Elements](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/resources/templates/labs/TestMC.html#L8)
[JavaScript Hiding Elements](https://github.com/PranavKambhampati/Tri3Drone/blob/AdminFormUI/src/main/resources/templates/labs/TestMC.html#L13)

**Comment by PranavKambhampati** [comment]
Hey Aryan, I agree with you that we should work on getting the questions that the admin enters into the form-maker inside the database. That way, once we have responses to those questions saved in the database, the analytics can be improved to display actual data.

**Comment by mhayescs19** [comment]
With the current progress on the database, for the earlier part of the week we may want to focus on the admin dashboard, which could display sample data from the items you mentioned. This would work out kinks in accessing real live data and displaying on the HTML page.

**Comment by nakulnandhakumar** [comment]
This is a good plan. There needs to be a custom role in Spring Security that can access this page and the page must only be whitelisted for admins. I will work on implementing this and also making the analytics page and any other admin page be accessible to only this role.

**Comment by PranavKambhampati** [comment]
Hey Aryan, it's great that you were able to find a solution to make the form more dynamic. It's also nice to hear that you were able to make progress on the database implementation. Once you and Michael figure out how to save data, I will be able to use it to generate the charts on the analytics page.

**Comment by mhayescs19** [comment]
I believe I have determined part of the solution different from what we discussed when we collaborated. I believe the @Autowired table repositories implemented properly. I believe that an @JoinColumn accessor might need to be implemented to store the specific id of the FK. My only confusion is how we store the id, since it still asks for the entire Form object not just the id.

**Comment by nakulnandhakumar** [comment]
Hey Aryan. I think that this is a good first step to connecting the forms with the database. A solution would be to use the JPA database object to save the information to specific part of the database or to create a list that can hold the form objects.
