### ISSUE TITLE
Practice MC on Monday + Review CB Video notes. After AP Exam, work on creating a small poll/quiz using JavaScript.

### ISSUE THREAD

**Issue by PranavKambhampati** [aryan114/Tri3Drone#68]
Score: 3/3
After exam, work on creating a small poll/quiz using JavaScript for logic, HTML for view and CSS for styling.

- [x] Conduct preliminary research on how to write JS logic
- [x] Look into how to integrate static content such as JS and CSS into SpringBoot project
- [x] HTML Page
- [x] CSS styling
- [x] JavaScript logic - array of questions and methods to produce questions in a random order
- [x] Integrate with project - add to navbar and create mapping
- [x] Re-Deploy project and make sure that quiz is working

RunTime Link: [LINK](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/labs/PranavJSPoll)

Code Links:
HTML: [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/main.html)
CSS: [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/static/styles.css)
JS: [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/static/script.js)
Controller: [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/LabsController.java#L422-L425)

Resources Used to code:
https://www.youtube.com/watch?v=NYXG1gcjhBI
https://www.youtube.com/watch?v=oigfaZ5ApsM
https://www.youtube.com/watch?v=SHIMUoAJHYU
https://www.youtube.com/watch?v=riDzcEQbX6k [Note: this video was used as a resource to code most of the quiz logic and styling]
https://www.springboottutorial.com/spring-boot-with-static-content-css-and-javascript-js
**Reviewed by Aryan**

**Comment by jm1021** [comment]
I see some ideas forming.  Nice to see the links you are going through and that you are capturing some of that history.  This will be a great resource for you to refer back on over time.  I have a couple of things that I notice that could be problems...
1. JavaScript code looks like it has hard coded information.  I believe you with want to have that in background and have some sort of getElemById code to pull data from rendered page into JS.
2. I notice you are accumulating CSS code.  You should consider using BootStrap and researching it for your visuals.

I don't see a peer evaluation above. 4/3

**Comment by aryan114** [comment]
Looks good, verified by @aryan114 (Aryan)
