### ISSUE TITLE
Create connection between database and graphs

### ISSUE THREAD

**Issue by PranavKambhampati** [aryan114/Tri3Drone#72]
- [ ] Get chart.js working
- [ ] Pull data from database
- [ ] Display pie-chart utilizing that data

**Comment by aryan114** [comment]
Hey Pranav, I think this is a really solid goal as it will be an integral part for achieving our group polling based system. I think these goals should definitely be a step in the direction with the incorporation of a database and displaying the chart data. Overall I think this is a very good ticket and will definitely help us plan and code out project!

**Comment by mhayescs19** [comment]
This week we will have to work out how we will convert the raw DB data into the pie charts. We will have to decide if we want to store more calculated data (number of users responses, number of questions in a form, number of forms per admin etc) in the DB or have these values be calculated via logic code.

**Comment by nakulnandhakumar** [comment]
Yes, I think that this is a good goal and the next logical step for you to do. I don't know if if you actually need to store the percentages in the database after calculating them as just the numerical values are enough and percentages can be calculated using stored numerical values on the spot.

**Comment by mhayescs19** [comment]
We will need to theorize how we will effectively extract analytical data from the admin's perspective. Do you think storing their id in the Form entity is enough to be able to give them sudo access and be able to extract the necessary data?
