### ISSUE TITLE
Work on creating a form in order to display a simple form creater.

### ISSUE THREAD

**Issue by aryan114** [aryan114/Tri3Drone#74]
- [x] Research and watch videos on how to create a simple UI for someone to make a simple quiz
- [x] Will be the stepping stone for the Admin Form UI, admin can create a form and choose questions and the following answer choices
- [x] Should display the questions and answer choices
**Links to Code**
[Model](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Forms/CreateMC.java#L1)
[Controller](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/LabsController.java#L357)
[View](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/CreateMCPage.html#L1)
**Runtime Link**
[Link](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/labs/CreateMC)

**Reviewed by Pranav**

**Comment by PranavKambhampati** [comment]
Verified by Pranav Kambhampati

**Comment by jm1021** [comment]
Hi Aryan, you seem to have hit on all the requirements and are producing code.  Very positive.  In look at the code and seeing num1, num2, ... numN.   I immediately think they is likely a better way.  I believe if all you IDs are the same you can request a list into the controller from the form, it works that way in Python.  You should research that and find a more efficient way as your quiz should be dynamic to the number of questions.  5/3
