### ISSUE TITLE
Create pi chart with chart.js library

### ISSUE THREAD

**Issue by PranavKambhampati** [aryan114/Tri3Drone#79]
Link to ReadMe: [ReadMe](https://github.com/PranavKambhampati/Tri3Drone#readme)

Goal: Start building the analytics portion of the project where the responses from the forms will be visualized through pie, bar and doughnut graphs. This week was mainly about understanding the Chart.js library and how to use it to make simple graphs.

- [x] Look into chart.js or Google Chart API and decide which is better
- [x] Figure out how to import libraries/ Preliminary Research
- [x] Add sample data to array for testing
- [x] Generate chart
- [x] Look into how to embed chart onto HTML page
- [x] Also try to make bar graph using same data as pi chart

Runtime Link: [LINK](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/labs/Charts)
Link to a page where I experimented with the chart.js library. The data in these graphs was completely made up. The next goal is to work on connecting the database to these charts, so that the charts reflect the actual data from the database.

Charts Page HTML: [HTML LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/chart/charts.html)
Charts Page JS(for chart rendering): [JS LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/static/js/chartscript.js)
Chart Data Set 1 (1st row of charts): [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/static/js/chartscript.js#L5-L7)
Chart Data Set 2 (2nd row of charts): [LINK](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/static/js/chartscript.js#L54-L56)

Link to Next Ticket: [LINK](https://github.com/PranavKambhampati/Tri3Drone/projects/1#card-61116671)
My next goal is to mainly work with Michael to build the charts so that they reflect the actual data from the database (not random data). The charts that I made this week will serve as a template, where I just have to modify the data part of the JS file.

**Comment by mhayescs19** [comment]
Chart.js seems like it will work well with the database. We will need to create some sort of logic to formulate values from the raw data. We may also need to investigate how to pass Spring data into the js file itself.

**Comment by aryan114** [comment]
Looks good, it seems that there needs to be a connection between the Thyme-leaf spring data and the storage through Javascript, but looks really nice and professional.

**Comment by nakulnandhakumar** [comment]
I really love the smooth graphics and the smooth animations. The next step would be adding backend code that takes in numerical values and converts the data to a percentage and displays it on the pie chart or bar graph.

**Comment by jm1021** [comment]
RESTapi and JS is probably the best way to pull data into a graph.
