### ISSUE TITLE
Refining Admin Form Creator UI

### ISSUE THREAD

**Issue by mhayescs19** [aryan114/Tri3Drone#8]
- [x] Refine the view, displayed questions and answers should be on next page
- [x] Make form more dynamic, incorporate a list to be passed into the constructor, in order to personalize form with number of questions and number of possible responses
- [x] Make HTML more aesthetically pleasing 
 
**Goal/Self Reflection:** My goal this week was to display the created form on a new page and to also find a way to make the form more dynamic. I was able to accomplish the goal of showing the created form on a new page, however, I wasn't satisfied with how I made the form more dynamic. Currently, if you just type in the questions you desire (ex: you want 2 questions), then the form will only show 2 questions with populated results, with 3 other empty results. While this may be a solution, I am not pleased with it, and will look to either incorporate a list into the controller and research more this week or I will try to incorporate JavaScript files and HTML hidden variables in order to move through the number of questions the user requests for. 

**[Runtime Link](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/labs/CreateMC)**

**Links to Code:** 
[Model](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Forms/CreateMC.java#L1)
[Creating Form View](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/CreateMCPage.html#L1)
[Showing Form View](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/ShowMCPage.html#L1)
[Controller](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/LabsController.java#L371)
[Controller Part 2](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/LabsController.java#L442)

**Attempts to Find Solution **
[Ask for Questions Model](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Forms/AskQuestions.java#L1)
[Ask for Questions View](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/resources/templates/labs/AskQuestions.html#L1)

[**Link to Next Ticket**]
(https://github.com/PranavKambhampati/Tri3Drone/issues/67)
My next ticket is for me to be able to connect the Admin Form to the database in order for it to be pushed to the student roles. I want to also find a cleaner solution to making the form more dynamic.

**Comment by mhayescs19** [comment]
- [ ] Basic form with question and response creation
- [ ] Send data to backend, but does not necessarily have to be stored to the database

**Comment by PranavKambhampati** [comment]
Hey Aryan, the refinements that you made to the form creator are really visible, with the HTML code looking better, allowing for the UI to be more pleasing to look at. I also noticed that you now display the created form on a separate page, which I believe is a step in the right direction. I think your next goal of adding the create-form data to a database is solid. Overall, nice work!

**Comment by mhayescs19** [comment]
Nice improvements displaying the created form on a new page. This week I found an example with the [@PathVariable annotation](https://youtu.be/tioMkaGW8Is?t=964), so if you want to create a more dynamic interface, that might be an option if each page has one question that uses that PathVariable with a template HTML page.

**Comment by nakulnandhakumar** [comment]
I really like the improvements you made to the UI. I think this is important because the form creation page is more intuitive and helpful to the user in terms of them understanding what is going on. Fewer instructions are needed because of this. I also think that connecting the form to the database is the logical next step.

**Comment by jm1021** [comment]
I would look at an add button to get dynamic you want.  I have see this is done in JS.
