### ISSUE TITLE
Finalize Database Integration

### ISSUE THREAD

**Issue by mhayescs19** [aryan114/Tri3Drone#80]
- [x] Deploy new MySQL DB from [AWS RDS](https://aws.amazon.com/rds/) and connection to MySQLWorkbench
- Resources: [RDS creation](https://www.youtube.com/watch?v=xJQS9MMUaxU), [connection to MySQLWorkbench](https://www.youtube.com/watch?v=Ng_zi11N4_c), [connection with Hibernate](https://medium.com/@ryanzhou7/using-aws-rds-for-your-spring-boot-app-ca8f4b09c9b8)
- [x] Add new tables to DB from updated [code model](https://app.diagrams.net/#G1YQfYtAZxYDmNi8eKqBqojASZfy1qRlAh) using MySQLWorkbench
- Resources: [javax.persistance implementation with JPA Repository](https://www.youtube.com/watch?v=8SGI_XS5OPw)
- [x] Test database some of CRUD via HTML pages
- [ ] Work with @nakulnandhakumar to integrate Spring Security users into database User table

**Achievements**
- Database in accessible in code through [jdbc:mysql link](https://github.com/PranavKambhampati/Tri3Drone/blob/16d716e35bbf01c027a5f936cf7b15bf72235621/src/main/resources/application.properties#L4) which integrates with hibernate/javax.persistence using an AWS RDS instance
- [User POJO generates User table](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/mysql/models/User.java) and matches directly with database
- [CRUD DB Example Controller](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/mysql/DbExampleController.java)
- Runtime Links: [Create](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/db/createUser), [Read](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/db/listAllUsers), & [Delete](http://ec2-34-217-90-30.us-west-2.compute.amazonaws.com/db/deleteUser)

**Comment by PranavKambhampati** [comment]
Hey Michael, I think the progress you have made with setting up the database is outstanding. The schema that you have created matches what we talked about in class, so I really do think we'll be able to store our data in an organized manner. Nice work!
