### ISSUE TITLE
Revise CRUD Implementations Focusing on the "U" and "D"

### ISSUE THREAD

**Issue by mhayescs19** [aryan114/Tri3Drone#86]
- [x] Complete ORM setup for necessary entities for form creation
- Resources: [ORM OneToMany/ManyToOne with **mapping by=""** ](https://www.youtube.com/watch?v=8mUPvdDGoLQ&t=324s), [@JoinColumn](https://www.journaldev.com/2924/hibernate-one-to-many-mapping-annotation)
- Code snippets: [Form.java](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/mysql/models/Form.java), [FormQuestion.java](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/mysql/models/FormQuestion.java)
- [x] Work with the rest of the team to provide database access
- @nakulnandhakumar Spring Security - [adding database users to SS credentials](https://github.com/PranavKambhampati/Tri3Drone/blob/ffa9d4e8bab4e40e4afe97120c55fa262d2ad85f/src/main/java/com/example/demo/Security/ApplicationSecurityConfig.java#L53-L64), [class created to determine user ID from anywhere in the website](https://github.com/PranavKambhampati/Tri3Drone/blob/master/src/main/java/com/example/demo/Security/PrincipalUserService.java)
- @aryan114 Form Creator - [@Bean accessors and saving user results to Form and FormQuestion entities ](https://github.com/PranavKambhampati/Tri3Drone/blob/cf588489bef80a779790230edb7101fb5d4ad6bd/src/main/java/com/example/demo/MCController.java#L79-L186)(needs @JoinColumn for @ManyToOne relationships to save to DB???)

**Comment by PranavKambhampati** [comment]
Hey Michael, I think your goals are really going to allow us to integrate the database into our project, allowing us to store data from the forms and Spring Security. This will also allow us to develop the analytics page to reflect actual data, so I think your goals are really going to help us advance our project!

**Comment by aryan114** [comment]
Hey Michael, I think your goals are great in order for us to integrate the database and store data from the forms, Spring Security, and the charts. This will definitely impact our project!

**Comment by nakulnandhakumar** [comment]
Hey Michael. I think that your goals look good. The ORM relationships are necessary for analytics purposes and for admins to access data from form answers. Thank you for the help with integrating Spring Security with the DB as well. The next step would be to connect actual forms with these relationships and connect form responses with a specific user.

**Comment by PranavKambhampati** [comment]
Hey Michael, I think that you have made a lot of progress this week, working with Aryan and Nakul. I think we're in the final stretch of our project - once we have the database implementation and the APIs to get data finished, I think we're going to be really close to being done with our project.

**Comment by aryan114** [comment]
Hey Michael, I think you made a lot of progress this week on the database. I think once we finish the database implementation for the admin form, then I think we'll be done. Thanks for the help this week.
