### ISSUE TITLE
Create RestAPI controller to get data from database

### ISSUE THREAD

**Issue by PranavKambhampati** [aryan114/Tri3Drone#92]
- [x] Preliminary Research on how to get data
- [x] Use Mr. M's code to try to get some data
- [x] Research how to utilize data from database in JavaScript

Goal: To create a rest API to get data from the database. Actual version can't be implemented until data is inputted through the form (what Aryan is working on). I've never done this before, so I just spent most of my time experimenting. I used Mr. M's code in order to get an understanding of how APIs are going to facilitate the retrieval of data. I will be working with @mhayescs19 to get data from the database, which will then be used to update the charts in the analytics category.

[LINK to practice code](https://github.com/PranavKambhampati/Tri3Drone/blob/GetforCharts/src/main/java/com/example/demo/ChartjsCharts/GetData.java)

[Mr. M's code that I used](https://github.com/nighthawkcoders/nighthawk_csa/blob/master/src/main/java/com/nighthawk/csa/PersonSqlMvcController.java#L83-L130)

**Comment by aryan114** [comment]
Hi Pranav, this seems like a good start. I think that this will definitely be a good compliment to the admin database setup that I am currently working on with Michael. I like that you are also experimenting with SQL as well.

**Comment by mhayescs19** [comment]
This is great that you were able to get this to work. This API process will be integral in order to share analytics since we will need to be able to give endpoints to other teams for them to access specific form results.

**Comment by nakulnandhakumar** [comment]
I agree with everyone else, this is great, especially for me as I can use this REST API to pull down the user information data associated with the user who has logged in. Also this will be crucial for sharing form analytics data between groups.
